version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SERVICENAME}_service
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_GOOGLE_REDIRECT_URI=${VITE_GOOGLE_REDIRECT_URI:-http://localhost:5173/auth/google/callback}
    networks:
      - enid_service_network

networks:
  enid_service_network:
    external: true